spring:
  datasource:
    #url: jdbc:postgresql://10.11.1.13:5432/postgres
    #username: postgres
    #password: password

    url: jdbc:postgresql://localhost:5432/aplication
    #url: jdbc:postgresql://10.11.3.177:5432/aplication

    username: postgres
    password: root2013

    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: beca-service
  profiles:
    active: dev

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://gatewayservice:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
